/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  theme: {
    extend: {
      fontFamily: {
        'cairo': ['Cairo', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      colors: {
        primary: {
          DEFAULT: 'var(--primary)',
          50: 'rgba(var(--primary-rgb), 0.05)',
          100: 'rgba(var(--primary-rgb), 0.1)',
          200: 'rgba(var(--primary-rgb), 0.2)',
          300: 'rgba(var(--primary-rgb), 0.3)',
          400: 'rgba(var(--primary-rgb), 0.4)',
          500: 'rgba(var(--primary-rgb), <alpha-value>)',
          600: 'var(--primary-dark)',
          700: 'rgba(var(--primary-rgb), 0.7)',
          800: 'rgba(var(--primary-rgb), 0.8)',
          900: 'rgba(var(--primary-rgb), 0.9)',
        },
        accent: {
          light: 'var(--accent)',
          DEFAULT: 'var(--accent)',
          dark: 'var(--accent-dark)',
        },
        themed: {
          bg: 'var(--bg-main)',
          'bg-sec': 'var(--bg-secondary)',
          'bg-ter': 'var(--bg-tertiary)',
          text: 'var(--text-main)',
          'text-sec': 'var(--text-secondary)',
          'text-ter': 'var(--text-tertiary)',
          'on-primary': 'var(--text-on-primary)',
          border: 'var(--border-color)',
          'border-light': 'var(--border-light)',
        },
        neutral: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        slate: {
          50: 'rgba(var(--primary-rgb), 0.02)',
          100: 'rgba(var(--primary-rgb), 0.05)',
          200: 'rgba(var(--primary-rgb), 0.1)',
          300: 'rgba(var(--primary-rgb), 0.2)',
          400: 'rgba(var(--primary-rgb), 0.4)',
          500: 'rgba(var(--primary-rgb), 0.6)',
          600: 'rgba(var(--primary-rgb), 0.7)',
          700: 'rgba(var(--primary-rgb), 0.8)',
          800: 'rgba(var(--primary-rgb), 0.9)',
          900: 'var(--text-main)',
        },
        tech: {
          blue: '#1a365d',
          cyan: '#164e63',
          gray: '#2d3748',
          silver: '#cbd5e1',
        },
        success: 'var(--success)',
        warning: 'var(--warning)',
        error: 'var(--error)',
        info: 'var(--info)',
      },
      fontSize: {
        'xs': '0.75rem',
        'sm': '0.875rem',
        'base': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
      },
      boxShadow: {
        'premium': '0 10px 30px -5px rgba(var(--primary-rgb), 0.08), 0 5px 15px -3px rgba(var(--primary-rgb), 0.03)',
        'premium-lg': '0 20px 40px -8px rgba(var(--primary-rgb), 0.12), 0 10px 20px -5px rgba(var(--primary-rgb), 0.05)',
        'premium-xl': '0 35px 70px -12px rgba(var(--primary-rgb), 0.18), 0 15px 30px -8px rgba(var(--primary-rgb), 0.08)',
        'formal': '0 4px 6px -1px rgba(var(--primary-rgb), 0.05), 0 2px 4px -1px rgba(var(--primary-rgb), 0.03)',
        'formal-lg': '0 10px 15px -3px rgba(var(--primary-rgb), 0.1), 0 4px 6px -2px rgba(var(--primary-rgb), 0.05)',
        'glow': '0 0 20px rgba(var(--primary-rgb), 0.25)',
        'glow-lg': '0 0 35px rgba(var(--primary-rgb), 0.35)',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-up': 'slideUp 0.8s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slideDown 0.8s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-right': 'slideRight 0.8s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in': 'scaleIn 0.6s cubic-bezier(0.16, 1, 0.3, 1)',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      borderRadius: {
        'xs': '0.25rem',
        'sm': '0.375rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
      },
    },
  },
  plugins: [],
  corePlugins: {
    textAlign: true,
  },
}