services:
  # 1. Jobify Backend (Node.js)
  - type: web
    name: jobify-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: "mongodb+srv://mohamed:m123456m@cluster0.llziker.mongodb.net/smart-recruitment?appName=Cluster0"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
      - key: OPENAI_API_KEY
        value: "sk-placeholder-not-required-for-local-dev"
      - key: JWT_COOKIE_EXPIRE
        value: "30"
  # 3. Jobify Client (Static Site)
  - type: web
    name: jobify-client
    env: static
    rootDir: client
    buildCommand: npm install && CI=false npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
